# Generated by Django 6.0.3 on 2026-04-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_commande_localisation_commande_photo_colis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='numero',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='N° Paiement'),
        ),
    ]
