# Generated by Django 6.0.3 on 2026-04-03 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock')], max_length=10)),
                ('quantite', models.IntegerField(verbose_name='Quantité')),
                ('quantite_avant', models.IntegerField(verbose_name='Stock avant')),
                ('quantite_apres', models.IntegerField(verbose_name='Stock après')),
                ('reference_doc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf Document (CMD, BON, etc.)')),
                ('source', models.CharField(choices=[('ACHAT', 'Achat fournisseur'), ('VENTE', 'Vente client'), ('AJUSTEMENT', 'Ajustement manuel'), ('RETOUR', 'Retour article')], default='VENTE', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='produits.produit')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date'],
            },
        ),
    ]
