# Generated by Django 6.0.3 on 2026-04-04 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_produit_achat_devise_produit_conversion_unit_and_more'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('MAGASIN', 'Magasin (Stock principal)'), ('BOUTIQUE', 'Boutique (Point de vente)')], default='MAGASIN', max_length=10)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
            },
        ),
        migrations.RemoveField(
            model_name='mouvementstock',
            name='source',
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='unite',
            field=models.CharField(default='PIECE', max_length=20),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite',
            field=models.IntegerField(verbose_name='Quantité (base)'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite_apres',
            field=models.IntegerField(default=0, verbose_name='Stock après'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='quantite_avant',
            field=models.IntegerField(default=0, verbose_name='Stock avant'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='reference_doc',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Réf Doc'),
        ),
        migrations.AlterField(
            model_name='mouvementstock',
            name='type',
            field=models.CharField(choices=[('ENTREE', 'Entrée de stock'), ('SORTIE', 'Sortie de stock'), ('TRANSFERT', 'Transfert inter-sites'), ('AJUSTEMENT', 'Ajustement manuel')], max_length=12),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='localisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.localisation'),
        ),
        migrations.CreateModel(
            name='TransfertStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('PROPOSE', 'En attente'), ('VALIDE', 'Validé pour préparation'), ('EXPEDIE', 'En transit'), ('RECU', 'Reçu en boutique'), ('ANNULE', 'Annulé')], default='PROPOSE', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_crees', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_entrants', to='stock.localisation')),
                ('provenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts_sortants', to='stock.localisation')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_valides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransfertItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_demandee', models.IntegerField()),
                ('quantite_reelle', models.IntegerField(default=0, help_text='Quantité réellement expédiée/reçue')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.produit')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.transfertstock')),
            ],
        ),
        migrations.CreateModel(
            name='StockParLocalisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(default=0, help_text='Quantité en unité secondaire (pièces)')),
                ('localisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventaire', to='stock.localisation')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_locations', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Stock par Localisation',
                'verbose_name_plural': 'Stocks par Localisation',
                'unique_together': {('produit', 'localisation')},
            },
        ),
    ]
