# Generated by Django 6.0.3 on 2026-04-03 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom commercial')),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence fabricant')),
                ('marque', models.CharField(max_length=100, verbose_name='Marque')),
                ('prix_achat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de vente')),
                ('quantite', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.IntegerField(default=5, verbose_name="Seuil d'alerte")),
                ('code_barre', models.CharField(max_length=50, unique=True, verbose_name='Code-barres')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Photo du produit')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.categorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
            },
        ),
    ]
