# Generated by Django 6.0.3 on 2026-04-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_marque_alter_produit_marque_alter_produit_prix_achat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='achat_devise',
            field=models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='GNF', max_length=3, verbose_name="Devise d'achat"),
        ),
        migrations.AddField(
            model_name='produit',
            name='conversion_unit',
            field=models.IntegerField(default=20, help_text="Combien d'unités secondaires dans une unité principale (ex: 20 pièces dans 1 carton)"),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_achat_devise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Prix d'achat (Devise)"),
        ),
        migrations.AddField(
            model_name='produit',
            name='taux_change_achat',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12, verbose_name='Taux de change (Achat)'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_principale',
            field=models.CharField(default='CARTON', max_length=20, verbose_name='Unité principale'),
        ),
        migrations.AddField(
            model_name='produit',
            name='unite_secondaire',
            field=models.CharField(default='PIECE', max_length=20, verbose_name='Unité secondaire'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat (Equiv. GNF)"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente (GNF)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(default=0, verbose_name='Quantité totale (Unité secondaire)'),
        ),
    ]
