# Generated by Django 6.0.3 on 2026-04-27 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0003_produit_achat_devise_produit_conversion_unit_and_more'),
        ('stock', '0002_localisation_remove_mouvementstock_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfertitem',
            options={'verbose_name': 'Article Transfert', 'verbose_name_plural': 'Articles Transfert'},
        ),
        migrations.AlterModelOptions(
            name='transfertstock',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Transfert de Stock', 'verbose_name_plural': 'Transferts de Stock'},
        ),
        migrations.AddField(
            model_name='stockparlocalisation',
            name='date_maj',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transfertstock',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='transfertitem',
            unique_together={('transfert', 'produit')},
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['-date'], name='stock_mouve_date_9fc233_idx'),
        ),
        migrations.AddIndex(
            model_name='mouvementstock',
            index=models.Index(fields=['produit', '-date'], name='stock_mouve_produit_7ca2b4_idx'),
        ),
        migrations.AddIndex(
            model_name='stockparlocalisation',
            index=models.Index(fields=['localisation', 'quantite'], name='stock_stock_localis_8d129a_idx'),
        ),
    ]
