# Generated by Django 6.0.3 on 2026-04-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_tentative',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tentatives_echouees',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
