# Generated by Django 6.0.3 on 2026-05-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0003_add_magasinier_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Numéro de téléphone'),
        ),
    ]
