# Generated by Django 6.0.3 on 2026-04-27 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditlog_delete_logactivite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-date'], 'verbose_name': "Log d'audit / Activité", 'verbose_name_plural': "Logs d'audit / Activité"},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='date_evenement',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date (Mobile)'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Mobile)'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ip_adresse',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP (Mobile)'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('VENTE', 'Vente effectuée'), ('STOCK_ENTREE', 'Réapprovisionnement'), ('STOCK_SORTIE', 'Sortie de stock'), ('ACCES', 'Attribution accès'), ('SUPPRESSION', 'Suppression'), ('AUTRE', 'Autre action')], default='AUTRE', max_length=20, verbose_name='Type (Mobile)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(max_length=255, verbose_name='Action (Web)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date (Web)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='Détails (Web)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP (Web)'),
        ),
    ]
