# Generated by Django 6.0.3 on 2026-04-04 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produits', '0003_produit_achat_devise_produit_conversion_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('pays', models.CharField(default='Guinée', max_length=100)),
                ('type', models.CharField(choices=[('LOCAL', 'Fournisseur Local'), ('INTERNATIONAL', 'Importateur / International')], default='LOCAL', max_length=20)),
                ('devise_par_defaut', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='GNF', max_length=3)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='CommandeAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='N° Bon de Commande')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYEE', 'Envoyée au fournisseur'), ('RECUE', 'Marchandise Reçue (En Stock)'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('devise', models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US'), ('EUR', 'Euro')], default='USD', max_length=3)),
                ('taux_change', models.DecimalField(decimal_places=4, default=1, help_text='Taux pour conversion en GNF', max_digits=12)),
                ('total_devise', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_gnf', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('date_commande', models.DateField(verbose_name='Date de commande')),
                ('date_reception_prevue', models.DateField(blank=True, null=True)),
                ('date_reception_reelle', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_crees', to=settings.AUTH_USER_MODEL)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achats', to='achats.fournisseur')),
            ],
            options={
                'verbose_name': "Commande d'Achat",
                'verbose_name_plural': "Commandes d'Achat",
                'ordering': ['-date_commande'],
            },
        ),
        migrations.CreateModel(
            name='LigneAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_cartons', models.IntegerField(verbose_name='Quantité (Cartons)')),
                ('quantite_pieces', models.IntegerField(editable=False, verbose_name='Equiv. Pièces')),
                ('prix_unitaire_devise', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix Unitaire (Devise)')),
                ('sous_total_devise', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('sous_total_gnf', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='achats.commandeachat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produits.produit')),
            ],
            options={
                'verbose_name': "Ligne d'Achat",
                'verbose_name_plural': "Lignes d'Achat",
            },
        ),
    ]
