# Generated by Django 6.0.3 on 2026-04-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0001_initial'),
        ('stock', '0002_localisation_remove_mouvementstock_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='localisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_site', to='stock.localisation'),
        ),
        migrations.AddField(
            model_name='commande',
            name='photo_colis',
            field=models.ImageField(blank=True, null=True, upload_to='colis/'),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_remise',
            field=models.CharField(choices=[('FIXE', 'Montant fixe (GNF)'), ('POURCENT', 'Pourcentage (%)')], default='POURCENT', max_length=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='preuve_paiement',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/preuves/'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valeur Remise'),
        ),
    ]
