# Generated by Django 6.0.3 on 2026-04-03 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marques/')),
            ],
        ),
        migrations.AlterField(
            model_name='produit',
            name='marque',
            field=models.CharField(max_length=100, verbose_name='Marque (Texte)'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix_vente',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix de vente'),
        ),
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nouveau_prix', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prix', to='produits.produit')),
            ],
            options={
                'verbose_name': 'Historique de Prix',
                'verbose_name_plural': 'Historiques de Prix',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='marque_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='produits.marque', verbose_name='Marque'),
        ),
    ]
