# Generated by Django 6.0.3 on 2026-04-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriedepense',
            name='budget_mensuel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget mensuel (GNF)'),
        ),
        migrations.AddField(
            model_name='depense',
            name='devise',
            field=models.CharField(choices=[('GNF', 'Franc Guinéen'), ('USD', 'Dollar US')], default='GNF', max_length=3),
        ),
        migrations.AddField(
            model_name='depense',
            name='montant_gnf',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depense',
            name='periodicite',
            field=models.CharField(choices=[('JOUR', 'Journalier'), ('SEMAINE', 'Hebdomadaire'), ('MOIS', 'Mensuel'), ('AN', 'Annuel')], default='JOUR', max_length=20),
        ),
        migrations.AddField(
            model_name='depense',
            name='preuve',
            field=models.ImageField(blank=True, null=True, upload_to='depenses/preuves/'),
        ),
        migrations.AddField(
            model_name='depense',
            name='taux',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
