# Generated by Django 6.0.3 on 2026-04-08 15:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_categoriedepense_budget_mensuel_depense_devise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code Compte')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du compte')),
                ('type', models.CharField(choices=[('ACTIF', 'Actif (Caisse, Banque, Stock)'), ('PASSIF', 'Passif (Dettes, Capitaux)'), ('CHARGE', 'Charge (Dépenses, Achats)'), ('PRODUIT', 'Produit (Ventes, Revenus)')], max_length=10)),
            ],
            options={
                'verbose_name': 'Compte Comptable',
                'verbose_name_plural': 'Comptes Comptables',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='numero',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True, verbose_name='N° Dépense'),
        ),
        migrations.CreateModel(
            name='JournalFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=50, unique=True, verbose_name='N° Journal')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('type_operation', models.CharField(choices=[('VENTE', 'Vente Client'), ('PAIEMENT', 'Paiement Client'), ('DEPENSE', 'Dépense / Frais'), ('ACHAT', 'Achat Fournisseur'), ('AJUSTEMENT', 'Ajustement Manuel')], max_length=20)),
                ('reference_doc', models.CharField(max_length=100, verbose_name='Réf Document')),
                ('description', models.TextField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('devise', models.CharField(default='GNF', max_length=3)),
                ('taux', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('montant_gnf', models.DecimalField(decimal_places=2, max_digits=15)),
                ('type_flux', models.CharField(choices=[('ENTREE', 'Encaissement (+)'), ('SORTIE', 'Décaissement (-)')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Financier',
                'verbose_name_plural': 'Journal Financier',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EcritureComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ecritures', to='finances.comptecomptable')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecritures', to='finances.journalfinancier')),
            ],
            options={
                'verbose_name': 'Écriture Comptable',
                'verbose_name_plural': 'Écritures Comptables',
            },
        ),
    ]
