# Generated by Django 6.0.3 on 2026-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_utilisateur_derniere_tentative_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('EMPLOYE', 'Employé'), ('MAGASINIER', 'Magasinier')], default='EMPLOYE', max_length=15),
        ),
    ]
