# Generated by Django 6.0.3 on 2026-04-03 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_action', models.CharField(choices=[('CONNEXION', 'Connexion'), ('VENTE', 'Vente effectuée'), ('STOCK_ENTREE', 'Réapprovisionnement'), ('STOCK_SORTIE', 'Sortie de stock'), ('ACCES', 'Attribution accès'), ('SUPPRESSION', 'Suppression')], max_length=20)),
                ('description', models.TextField()),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('ip_adresse', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'ordering': ['-date_evenement'],
            },
        ),
    ]
