# Generated by Django 6.0.3 on 2026-04-03 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='limite_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Limite de Crédit'),
        ),
        migrations.AddField(
            model_name='client',
            name='score_statut',
            field=models.CharField(choices=[('BON', 'Bon Payeur'), ('MOYEN', 'Moyen'), ('MAUVAIS', 'Mauvais Payeur'), ('BLOQUE', 'Bloqué Manuellement')], default='BON', max_length=10),
        ),
    ]
