# Generated by Django 6.0.3 on 2026-04-03 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True, verbose_name='N° Facture')),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('total_ttc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_regle', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reste_a_payer', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIELLE', 'Paiement partiel'), ('PAIEE', 'Payée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/%Y/%m/')),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
    ]
